Document: mingw-w64-libpcre
Title: Debian mingw-w64-libpcre Manual
Author: <insert document author here>
Abstract: This manual describes what mingw-w64-libpcre is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mingw-w64-libpcre/mingw-w64-libpcre.sgml.gz

Format: postscript
Files: /usr/share/doc/mingw-w64-libpcre/mingw-w64-libpcre.ps.gz

Format: text
Files: /usr/share/doc/mingw-w64-libpcre/mingw-w64-libpcre.text.gz

Format: HTML
Index: /usr/share/doc/mingw-w64-libpcre/html/index.html
Files: /usr/share/doc/mingw-w64-libpcre/html/*.html
